"""
Stable internal identifiers for IMIE analysts.

These identifiers are used by the AnalystRegistry and DecisionDirector.
They must remain stable even if analyst class names or display names change.
"""

ANALYST_TREND = "TREND"
ANALYST_SETUP = "SETUP"
ANALYST_ACCEPTANCE = "ACCEPTANCE"
ANALYST_RISK = "RISK"

ANALYST_STRUCTURE = "STRUCTURE"
ANALYST_LIQUIDITY = "LIQUIDITY"
ANALYST_AUCTION = "AUCTION"
ANALYST_PRESSURE = "PRESSURE"
ANALYST_PARTICIPATION = "PARTICIPATION"
ANALYST_VALUE = "VALUE"

ANALYST_ORDER_BLOCK = "ORDER_BLOCK"


CORE_ANALYST_IDS = (
    ANALYST_TREND,
    ANALYST_SETUP,
    ANALYST_ACCEPTANCE,
    ANALYST_RISK,
)


__all__ = [
    "ANALYST_TREND",
    "ANALYST_SETUP",
    "ANALYST_ACCEPTANCE",
    "ANALYST_RISK",
    "ANALYST_STRUCTURE",
    "ANALYST_LIQUIDITY",
    "ANALYST_AUCTION",
    "ANALYST_PRESSURE",
    "ANALYST_PARTICIPATION",
    "ANALYST_VALUE",
    "CORE_ANALYST_IDS",
    "ANALYST_ORDER_BLOCK"
]